# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4633f441bf68f4e4c8bac45cd90007c0a33e81a53a38f0b648e9638fcfd94fb826d51bc7f5e652e0ffa06af3132a103339864381f773efc546cecd0fbcaabbff

test:
  secret_key_base: 358bab453f869ccff66c9c5a69e6d8a9d0bfc91eef424b40786fc299cb037f3d338a04eca73edcdc0919ed798f17f114ddad94deda59c894535ee3cc696f4c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
